# GitHub labeler configuration: maps changed paths to labels
# Adjust labels to match your repository's label names

backend:
  - changed-files:
      - any-glob-to-any-file:
          - "src/**"
          - "Cargo.toml"
          - "npm/**"
          - "package.json"
          - "scripts/**"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"
          - "docs/**"
          - "README.md"
          - "tests/**"

chore:
  - changed-files:
      - any-glob-to-any-file:
          - "scripts/**"
          - "*.md"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "**/Cargo.lock"
          - "**/pnpm-lock.yaml"
          - "**/package-lock.json"
          - "**/yarn.lock"

# Note: labels must already exist in the repository.
