# GitHub labeler configuration: maps changed paths to labels
# Adjust labels to match your repository's label names

backend:
  - "src/**"
  - "Cargo.toml"
  - "Cargo.lock"

  - "npm/**"
  - "package.json"
  - "package-lock.json"

  - "scripts/**"

ci:
  - ".github/**"

  - "docs/**"
  - "README.md"

  - "tests/**"

chore:
  - "scripts/**"
  - "*.md"

# Note: labels must already exist in the repository. If you want me to create
# missing labels via the GitHub API, tell me and I will do that as a follow-up.
