packages:
  - npm/agentsync
  - website/docs

catalog:
  '@dallay/agentsync': 1.27.1
  '@semantic-release/changelog': ^6.0.3
  '@semantic-release/exec': ^7.1.0
  '@semantic-release/git': ^10.0.1
  '@semantic-release/github': ^12.0.2
  '@semantic-release/npm': ^13.1.3
  conventional-changelog-conventionalcommits: ^9.1.0
  semantic-release: ^25.0.2

minimumReleaseAge: 4320 # 3 days

minimumReleaseAgeExclude:
  - '@dallay/*'
  - '@biomejs/*'
