packages:
  - npm/agentsync

# catalog definition for the agentsync package

minimumReleaseAge: 4320 # 3 days

minimumReleaseAgeExclude:
  - '@dallay/*'

catalog:
  "@dallay/agentsync": "1.7.0"
  "semantic-release": "^25.0.2"
  "@semantic-release/changelog": "^6.0.3"
  "@semantic-release/exec": "^7.1.0"
  "@semantic-release/git": "^10.0.1"
  "@semantic-release/github": "^11.0.6"
  "@semantic-release/npm": "^12.0.2"
  "conventional-changelog-conventionalcommits": "^9.1.0"
