use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};

use sha2::{Digest, Sha256};
use tempfile::TempDir;

#[cfg(unix)]
fn agentsync_bin() -> &'static str {
    env!("CARGO_BIN_EXE_agentsync")
}

#[cfg(unix)]
fn run_agentsync(project_root: &Path, args: &[&str]) -> Output {
    let data_root = project_root.parent().unwrap().join(".local-data");
    run_agentsync_with_data_root(project_root, args, &data_root)
}

#[cfg(unix)]
fn run_agentsync_with_data_root(project_root: &Path, args: &[&str], data_root: &Path) -> Output {
    Command::new(agentsync_bin())
        .current_dir(project_root)
        .env("AGENTSYNC_DATA_DIR", data_root)
        .args(args)
        .output()
        .unwrap_or_else(|error| panic!("failed to run agentsync {:?}: {error}", args))
}

#[cfg(unix)]
fn ownership_manifest(project_root: &Path) -> PathBuf {
    let data_root = project_root.parent().unwrap().join(".local-data");
    ownership_manifest_at_data_root(&data_root)
}

#[cfg(unix)]
fn ownership_manifest_at_data_root(data_root: &Path) -> PathBuf {
    let ownership_root = data_root.join("agentsync/mcp-ownership");
    fs::read_dir(&ownership_root)
        .unwrap()
        .next()
        .unwrap()
        .unwrap()
        .path()
        .join("ownership.json")
}

#[cfg(unix)]
fn write_fixture(project_root: &Path) {
    fs::create_dir_all(project_root.join(".agents")).unwrap();
    fs::write(project_root.join(".agents/AGENTS.md"), "# hello\n").unwrap();
    fs::write(
        project_root.join(".agents/agentsync.toml"),
        "source_dir = \".\"\n\n[agents.claude]\nenabled = true\n\n[agents.claude.targets.instructions]\nsource = \"AGENTS.md\"\ndestination = \"CLAUDE.md\"\ntype = \"symlink\"\n",
    )
    .unwrap();
    fs::write(project_root.join("CLAUDE.md"), "original\n").unwrap();
}

#[test]
#[cfg(unix)]
fn test_revert_restores_pre_apply_file() {
    let temp_dir = TempDir::new().unwrap();
    let project_root = &temp_dir.path().join("project");
    fs::create_dir_all(project_root).unwrap();
    write_fixture(project_root);

    let apply = run_agentsync(project_root, &["apply"]);
    assert!(
        apply.status.success(),
        "apply failed:\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&apply.stdout),
        String::from_utf8_lossy(&apply.stderr)
    );
    assert!(project_root.join("CLAUDE.md").is_symlink());
    assert!(project_root.join("CLAUDE.md.bak").exists());

    let revert = run_agentsync(project_root, &["revert"]);
    assert!(
        revert.status.success(),
        "revert failed:\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&revert.stdout),
        String::from_utf8_lossy(&revert.stderr)
    );
    assert_eq!(
        fs::read_to_string(project_root.join("CLAUDE.md")).unwrap(),
        "original\n"
    );
    assert!(!project_root.join("CLAUDE.md").is_symlink());
    assert!(!project_root.join("CLAUDE.md.bak").exists());
    // Managed gitignore block is gone after an unfiltered revert.
    let gitignore = project_root.join(".gitignore");
    if gitignore.exists() {
        assert!(
            !fs::read_to_string(&gitignore).unwrap().contains("START"),
            "managed block should be removed"
        );
    }
}

#[test]
#[cfg(unix)]
fn mcp_revert_uses_ownership_journal_after_mcp_is_disabled() {
    let temp_dir = TempDir::new().unwrap();
    let project_root = temp_dir.path();
    write_fixture(project_root);
    let config_path = project_root.join(".agents/agentsync.toml");
    let config = fs::read_to_string(&config_path).unwrap();
    fs::write(
        &config_path,
        format!(
            "{config}\n[mcp]\nenabled = true\n\n[mcp_servers.fixture]\ncommand = \"fixture-server\"\n"
        ),
    )
    .unwrap();

    let apply = run_agentsync(project_root, &["apply"]);
    assert!(
        apply.status.success(),
        "{}",
        String::from_utf8_lossy(&apply.stderr)
    );
    let mcp_config = project_root.join(".mcp.json");
    assert!(mcp_config.exists());

    let config = fs::read_to_string(&config_path).unwrap();
    let updated_config = config.replace(
        "[mcp]\nenabled = true\n\n[mcp_servers.fixture]\ncommand = \"fixture-server\"\n",
        "[mcp]\nenabled = false\n",
    );
    assert_ne!(updated_config, config);
    fs::write(&config_path, updated_config).unwrap();

    let revert = run_agentsync(project_root, &["revert"]);
    assert!(
        revert.status.success(),
        "{}",
        String::from_utf8_lossy(&revert.stderr)
    );
    let output = String::from_utf8_lossy(&revert.stdout);
    assert!(
        output.contains("Restored MCP config"),
        "revert should restore the apply-time MCP snapshot even after MCP is disabled: {output}"
    );
    assert!(output.contains("Revert complete"), "{output}");
    assert!(
        !mcp_config.exists(),
        "revert should remove an MCP config generated by apply when no file existed before"
    );
    let gitignore = project_root.join(".gitignore");
    if gitignore.exists() {
        assert!(!fs::read_to_string(gitignore).unwrap().contains("START"));
    }
}

#[test]
#[cfg(unix)]
fn test_revert_dry_run_changes_nothing() {
    let temp_dir = TempDir::new().unwrap();
    let project_root = &temp_dir.path().join("project");
    fs::create_dir_all(project_root).unwrap();
    write_fixture(project_root);
    let apply = run_agentsync(project_root, &["apply"]);
    assert!(apply.status.success());

    let revert = run_agentsync(project_root, &["revert", "--dry-run"]);
    assert!(
        revert.status.success(),
        "revert --dry-run failed:\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&revert.stdout),
        String::from_utf8_lossy(&revert.stderr)
    );
    // Symlink AND backup both still present.
    assert!(project_root.join("CLAUDE.md").is_symlink());
    assert!(project_root.join("CLAUDE.md.bak").exists());
}

#[test]
#[cfg(unix)]
fn test_revert_keep_backups_preserves_bak() {
    let temp_dir = TempDir::new().unwrap();
    let project_root = &temp_dir.path().join("project");
    fs::create_dir_all(project_root).unwrap();
    write_fixture(project_root);
    assert!(run_agentsync(project_root, &["apply"]).status.success());

    let revert = run_agentsync(project_root, &["revert", "--keep-backups"]);
    assert!(
        revert.status.success(),
        "revert --keep-backups failed:\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&revert.stdout),
        String::from_utf8_lossy(&revert.stderr)
    );
    assert_eq!(
        fs::read_to_string(project_root.join("CLAUDE.md")).unwrap(),
        "original\n"
    );
    assert_eq!(
        fs::read_to_string(project_root.join("CLAUDE.md.bak")).unwrap(),
        "original\n"
    );
}

#[test]
#[cfg(unix)]
fn test_revert_keeps_gitignore_when_destination_errors() {
    let temp_dir = TempDir::new().unwrap();
    let project_root = &temp_dir.path().join("project");
    fs::create_dir_all(project_root).unwrap();
    fs::create_dir_all(project_root.join(".agents")).unwrap();
    fs::write(
        project_root.join(".agents/agentsync.toml"),
        "source_dir = \".\"\n\n[agents.claude]\nenabled = true\n\n[agents.claude.targets.instructions]\nsource = \"AGENTS.md\"\ndestination = \"/etc/passwd\"\ntype = \"symlink\"\n",
    )
    .unwrap();
    fs::write(
        project_root.join(".gitignore"),
        "# START AI Agent Symlinks\nCLAUDE.md\n# END AI Agent Symlinks\n",
    )
    .unwrap();

    let revert = run_agentsync(project_root, &["revert"]);

    assert!(
        !revert.status.success(),
        "unsafe destination should be an error"
    );
    let gitignore = fs::read_to_string(project_root.join(".gitignore")).unwrap();
    assert!(
        gitignore.contains("# START AI Agent Symlinks"),
        "managed gitignore block must remain when revert reports an error"
    );
}

#[test]
#[cfg(unix)]
fn test_revert_with_missing_nested_glob_source_reports_incomplete_and_keeps_gitignore() {
    let temp_dir = TempDir::new().unwrap();
    let project_root = &temp_dir.path().join("project");
    fs::create_dir_all(project_root).unwrap();
    fs::create_dir_all(project_root.join(".agents")).unwrap();
    let source_dir = project_root.join("docs/deep");
    fs::create_dir_all(&source_dir).unwrap();
    fs::write(source_dir.join("guide.md"), "# managed\n").unwrap();
    fs::write(
        project_root.join(".agents/agentsync.toml"),
        "source_dir = \".\"\n\n[agents.claude]\nenabled = true\n\n[agents.claude.targets.docs]\nsource = \"docs\"\ndestination = \"linked/{relative_path}/{file_name}\"\ntype = \"nested-glob\"\npattern = \"**/*.md\"\n",
    )
    .unwrap();

    let apply = run_agentsync(project_root, &["apply"]);
    assert!(
        apply.status.success(),
        "{}",
        String::from_utf8_lossy(&apply.stderr)
    );
    let destination = project_root.join("linked/deep/guide.md");
    assert!(
        destination.is_symlink(),
        "expected nested-glob link at {}\nstdout:\n{}\nstderr:\n{}",
        destination.display(),
        String::from_utf8_lossy(&apply.stdout),
        String::from_utf8_lossy(&apply.stderr)
    );
    let gitignore = fs::read_to_string(project_root.join(".gitignore")).unwrap();
    assert!(gitignore.contains("# START"));

    fs::remove_dir_all(project_root.join("docs")).unwrap();
    let revert = run_agentsync(project_root, &["revert"]);
    assert!(
        revert.status.success(),
        "{}",
        String::from_utf8_lossy(&revert.stderr)
    );
    assert!(
        destination.is_symlink(),
        "unknown nested-glob orphan is not inferred"
    );
    assert!(
        fs::read_to_string(project_root.join(".gitignore"))
            .unwrap()
            .contains("# START"),
        "incomplete revert must preserve the managed gitignore block"
    );
    let output = String::from_utf8_lossy(&revert.stdout);
    assert!(
        output.contains("Skipped: 1") || output.contains("skipped"),
        "{output}"
    );
}

#[test]
#[cfg(unix)]
fn test_revert_refuses_to_overwrite_user_file() {
    let temp_dir = TempDir::new().unwrap();
    let project_root = &temp_dir.path().join("project");
    fs::create_dir_all(project_root).unwrap();
    write_fixture(project_root);
    assert!(run_agentsync(project_root, &["apply"]).status.success());
    assert!(project_root.join("CLAUDE.md").is_symlink());
    assert!(project_root.join("CLAUDE.md.bak").exists());

    // User replaces the managed symlink with a regular file after apply.
    fs::remove_file(project_root.join("CLAUDE.md")).unwrap();
    fs::write(project_root.join("CLAUDE.md"), "user edit\n").unwrap();
    assert!(!project_root.join("CLAUDE.md").is_symlink());

    let _ = run_agentsync(project_root, &["revert"]);
    // User content is preserved and the backup is left in place for manual recovery.
    assert_eq!(
        fs::read_to_string(project_root.join("CLAUDE.md")).unwrap(),
        "user edit\n"
    );
    assert_eq!(
        fs::read_to_string(project_root.join("CLAUDE.md.bak")).unwrap(),
        "original\n"
    );
}

#[cfg(unix)]
fn write_mcp_fixture(project_root: &Path) {
    fs::create_dir_all(project_root.join(".agents")).unwrap();
    fs::write(project_root.join(".agents/AGENTS.md"), "# hello\n").unwrap();
    fs::write(
        project_root.join(".agents/agentsync.toml"),
        "source_dir = \".\"\n\n[mcp]\nenabled = true\n\n[mcp_servers.search]\ncommand = \"managed-search\"\nargs = [\"--managed\"]\n\n[agents.claude]\nenabled = true\n\n[agents.claude.targets.instructions]\nsource = \"AGENTS.md\"\ndestination = \"CLAUDE.md\"\ntype = \"symlink\"\n",
    )
    .unwrap();
    fs::write(
        project_root.join(".mcp.json"),
        r#"{"$schema":"https://example.test/mcp.json","inputs":[{"id":"workspace"}],"mcpServers":{"search":{"command":"user-search","args":["--user"]},"mine":{"command":"my-tool"}}}"#,
    )
    .unwrap();
}

#[test]
#[cfg(unix)]
fn test_apply_then_revert_restores_preexisting_mcp_config_exactly() {
    let temp_dir = TempDir::new().unwrap();
    let project_root = &temp_dir.path().join("project");
    fs::create_dir_all(project_root).unwrap();
    write_mcp_fixture(project_root);

    let apply = run_agentsync(project_root, &["apply"]);
    assert!(
        apply.status.success(),
        "apply failed:\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&apply.stdout),
        String::from_utf8_lossy(&apply.stderr)
    );
    let after_apply = fs::read_to_string(project_root.join(".mcp.json")).unwrap();
    let original = r#"{"$schema":"https://example.test/mcp.json","inputs":[{"id":"workspace"}],"mcpServers":{"search":{"command":"user-search","args":["--user"]},"mine":{"command":"my-tool"}}}"#;
    assert_ne!(after_apply, original);

    let revert = run_agentsync(project_root, &["revert"]);
    assert!(
        revert.status.success(),
        "revert failed:\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&revert.stdout),
        String::from_utf8_lossy(&revert.stderr)
    );
    assert_eq!(
        fs::read_to_string(project_root.join(".mcp.json")).unwrap(),
        original
    );
}

#[test]
#[cfg(unix)]
fn test_apply_then_revert_uses_symlinked_data_root_override() {
    use std::os::unix::fs::symlink;

    let temp_dir = TempDir::new().unwrap();
    let project_root = &temp_dir.path().join("project");
    let external_data = temp_dir.path().join("external-data");
    let data_root_link = temp_dir.path().join("data-root-link");
    fs::create_dir_all(project_root).unwrap();
    fs::create_dir_all(&external_data).unwrap();
    symlink(&external_data, &data_root_link).unwrap();
    write_mcp_fixture(project_root);
    let mcp_path = project_root.join(".mcp.json");
    let original = fs::read(&mcp_path).unwrap();

    let apply = run_agentsync_with_data_root(project_root, &["apply"], &data_root_link);
    assert!(
        apply.status.success(),
        "apply failed:\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&apply.stdout),
        String::from_utf8_lossy(&apply.stderr)
    );
    assert_ne!(fs::read(&mcp_path).unwrap(), original);
    assert!(ownership_manifest_at_data_root(&external_data).is_file());

    let revert = run_agentsync_with_data_root(project_root, &["revert"], &data_root_link);
    assert!(
        revert.status.success(),
        "revert failed:\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&revert.stdout),
        String::from_utf8_lossy(&revert.stderr)
    );
    assert_eq!(fs::read(&mcp_path).unwrap(), original);
    assert!(!ownership_manifest_at_data_root(&external_data).exists());
}

#[test]
#[cfg(unix)]
fn test_apply_rejects_data_root_inside_project_before_mcp_write() {
    let temp_dir = TempDir::new().unwrap();
    let project_root = &temp_dir.path().join("project");
    fs::create_dir_all(project_root).unwrap();
    write_mcp_fixture(project_root);
    let mcp_path = project_root.join(".mcp.json");
    let original = fs::read(&mcp_path).unwrap();
    let data_root = project_root.join(".local-data");

    let apply = run_agentsync_with_data_root(project_root, &["apply"], &data_root);

    assert!(
        !apply.status.success(),
        "apply must reject an ownership journal root inside the project\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&apply.stdout),
        String::from_utf8_lossy(&apply.stderr)
    );
    assert_eq!(fs::read(&mcp_path).unwrap(), original);
    assert!(
        !data_root.exists(),
        "rejected data root must not be created"
    );
}

#[test]
#[cfg(unix)]
fn test_apply_relative_project_then_revert_absolute_restores_mcp() {
    let temp_dir = TempDir::new().unwrap();
    let project_root = &temp_dir.path().join("project");
    fs::create_dir_all(project_root).unwrap();
    write_mcp_fixture(project_root);
    let mcp_path = project_root.join(".mcp.json");
    let original = fs::read(&mcp_path).unwrap();

    let apply = run_agentsync(project_root, &["apply", "--path", "."]);
    assert!(
        apply.status.success(),
        "apply failed:\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&apply.stdout),
        String::from_utf8_lossy(&apply.stderr)
    );

    let revert = run_agentsync(project_root, &["revert"]);
    assert!(
        revert.status.success(),
        "revert failed:\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&revert.stdout),
        String::from_utf8_lossy(&revert.stderr)
    );
    assert_eq!(fs::read(&mcp_path).unwrap(), original);
    assert!(!ownership_manifest(project_root).exists());
}

#[test]
#[cfg(unix)]
fn test_revert_removes_generated_mcp_config_when_it_still_matches_journal() {
    let temp_dir = TempDir::new().unwrap();
    let project_root = &temp_dir.path().join("project");
    fs::create_dir_all(project_root).unwrap();
    write_mcp_fixture(project_root);
    fs::remove_file(project_root.join(".mcp.json")).unwrap();

    let apply = run_agentsync(project_root, &["apply"]);
    assert!(
        apply.status.success(),
        "{}",
        String::from_utf8_lossy(&apply.stderr)
    );
    assert!(project_root.join(".mcp.json").is_file());
    let lock_path = ownership_manifest(project_root)
        .parent()
        .unwrap()
        .join("ownership.lock");
    assert!(lock_path.is_file());

    let revert = run_agentsync(project_root, &["revert"]);
    assert!(
        revert.status.success(),
        "{}",
        String::from_utf8_lossy(&revert.stderr)
    );
    assert!(!project_root.join(".mcp.json").exists());
    assert!(!ownership_manifest(project_root).exists());
    assert!(
        lock_path.is_file(),
        "the persistent ownership lock is retained"
    );
}

#[test]
#[cfg(unix)]
fn test_overwrite_revert_restores_raw_mcp_config() {
    let temp_dir = TempDir::new().unwrap();
    let project_root = &temp_dir.path().join("project");
    fs::create_dir_all(project_root).unwrap();
    write_mcp_fixture(project_root);
    let config_path = project_root.join(".agents/agentsync.toml");
    let config = fs::read_to_string(&config_path).unwrap().replace(
        "[mcp]\nenabled = true",
        "[mcp]\nenabled = true\nmerge_strategy = \"overwrite\"",
    );
    fs::write(&config_path, config).unwrap();
    let original = fs::read(project_root.join(".mcp.json")).unwrap();

    let apply = run_agentsync(project_root, &["apply"]);
    assert!(
        apply.status.success(),
        "{}",
        String::from_utf8_lossy(&apply.stderr)
    );
    assert_ne!(fs::read(project_root.join(".mcp.json")).unwrap(), original);

    let revert = run_agentsync(project_root, &["revert"]);
    assert!(
        revert.status.success(),
        "{}",
        String::from_utf8_lossy(&revert.stderr)
    );
    assert_eq!(fs::read(project_root.join(".mcp.json")).unwrap(), original);
}

#[test]
#[cfg(unix)]
fn test_reapply_preserves_first_mcp_baseline() {
    let temp_dir = TempDir::new().unwrap();
    let project_root = &temp_dir.path().join("project");
    fs::create_dir_all(project_root).unwrap();
    write_mcp_fixture(project_root);
    let original = fs::read(project_root.join(".mcp.json")).unwrap();

    let first_apply = run_agentsync(project_root, &["apply"]);
    assert!(
        first_apply.status.success(),
        "{}",
        String::from_utf8_lossy(&first_apply.stderr)
    );
    let config_path = project_root.join(".agents/agentsync.toml");
    let config = fs::read_to_string(&config_path)
        .unwrap()
        .replace("managed-search", "managed-search-v2");
    fs::write(&config_path, config).unwrap();
    let second_apply = run_agentsync(project_root, &["apply"]);
    assert!(
        second_apply.status.success(),
        "{}",
        String::from_utf8_lossy(&second_apply.stderr)
    );

    let revert = run_agentsync(project_root, &["revert"]);
    assert!(
        revert.status.success(),
        "{}",
        String::from_utf8_lossy(&revert.stderr)
    );
    assert_eq!(fs::read(project_root.join(".mcp.json")).unwrap(), original);
}

#[test]
#[cfg(unix)]
fn test_reapply_rejects_foreign_mcp_content_without_changing_config_or_journal() {
    let temp_dir = TempDir::new().unwrap();
    let project_root = &temp_dir.path().join("project");
    fs::create_dir_all(project_root).unwrap();
    write_mcp_fixture(project_root);
    let config_path = project_root.join(".mcp.json");
    let original = fs::read(&config_path).unwrap();

    let first_apply = run_agentsync(project_root, &["apply"]);
    assert!(
        first_apply.status.success(),
        "{}",
        String::from_utf8_lossy(&first_apply.stderr)
    );
    let applied = fs::read(&config_path).unwrap();
    let manifest_path = ownership_manifest(project_root);
    let manifest_before = fs::read(&manifest_path).unwrap();
    let manifest: serde_json::Value = serde_json::from_slice(&manifest_before).unwrap();
    let record = manifest["configs"]
        .as_object()
        .unwrap()
        .values()
        .next()
        .unwrap();
    let hash = |bytes: &[u8]| {
        Sha256::digest(bytes)
            .iter()
            .map(|byte| format!("{byte:02x}"))
            .collect::<String>()
    };
    assert_eq!(
        record["original_content"],
        String::from_utf8(original.clone()).unwrap()
    );
    assert_eq!(record["pre_write_sha256"], hash(&original));
    assert_eq!(record["applied_sha256"], hash(&applied));

    let foreign = br#"{"mcpServers":{"foreign":{"command":"foreign-tool"}}}"#;
    fs::write(&config_path, foreign).unwrap();
    let second_apply = run_agentsync(project_root, &["apply"]);

    assert!(
        !second_apply.status.success(),
        "apply must fail closed when the live MCP config matches neither ownership hash\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&second_apply.stdout),
        String::from_utf8_lossy(&second_apply.stderr)
    );
    assert_eq!(fs::read(&config_path).unwrap(), foreign);
    assert_eq!(fs::read(&manifest_path).unwrap(), manifest_before);
}

#[test]
#[cfg(unix)]
fn test_explicit_mcp_journal_rebase_keeps_original_snapshot_for_revert() {
    let temp_dir = TempDir::new().unwrap();
    let project_root = &temp_dir.path().join("project");
    fs::create_dir_all(project_root).unwrap();
    write_mcp_fixture(project_root);
    let config_path = project_root.join(".mcp.json");
    let original = fs::read(&config_path).unwrap();

    let first_apply = run_agentsync(project_root, &["apply"]);
    assert!(
        first_apply.status.success(),
        "{}",
        String::from_utf8_lossy(&first_apply.stderr)
    );
    let mut edited: serde_json::Value =
        serde_json::from_slice(&fs::read(&config_path).unwrap()).unwrap();
    edited["mcpServers"]["search"]["command"] = serde_json::json!("manual-edit");
    let edited_content = serde_json::to_vec(&edited).unwrap();
    fs::write(&config_path, &edited_content).unwrap();

    let reapply = run_agentsync(project_root, &["apply", "--rebase-mcp-journal"]);
    assert!(
        reapply.status.success(),
        "explicit journal rebase failed:\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&reapply.stdout),
        String::from_utf8_lossy(&reapply.stderr)
    );
    assert!(
        String::from_utf8_lossy(&reapply.stderr).contains("Explicit MCP ownership rebase accepted"),
        "the opt-in rebase should explain its restore consequence: {}",
        String::from_utf8_lossy(&reapply.stderr)
    );
    let reapplied: serde_json::Value =
        serde_json::from_slice(&fs::read(&config_path).unwrap()).unwrap();
    assert!(
        reapplied["mcpServers"]["search"].is_object(),
        "managed MCP entry was lost: {reapplied}"
    );

    let manifest: serde_json::Value =
        serde_json::from_slice(&fs::read(ownership_manifest(project_root)).unwrap()).unwrap();
    let record = manifest["configs"]
        .as_object()
        .unwrap()
        .values()
        .next()
        .unwrap();
    assert_eq!(
        record["original_content"],
        String::from_utf8(original.clone()).unwrap()
    );
    assert_eq!(record["agent_ids"][0], "claude");
    let sha256_hex = |bytes: &[u8]| {
        Sha256::digest(bytes)
            .iter()
            .map(|byte| format!("{byte:02x}"))
            .collect::<String>()
    };
    assert_eq!(record["pre_write_sha256"], sha256_hex(&edited_content));
    assert_eq!(
        record["applied_sha256"],
        sha256_hex(&fs::read(&config_path).unwrap())
    );

    let revert = run_agentsync(project_root, &["revert"]);
    assert!(
        revert.status.success(),
        "revert failed:\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&revert.stdout),
        String::from_utf8_lossy(&revert.stderr)
    );
    assert_eq!(fs::read(&config_path).unwrap(), original);
}

#[test]
#[cfg(unix)]
fn test_revert_preserves_post_apply_mcp_edit_and_retains_journal() {
    let temp_dir = TempDir::new().unwrap();
    let project_root = &temp_dir.path().join("project");
    fs::create_dir_all(project_root).unwrap();
    write_mcp_fixture(project_root);
    assert!(run_agentsync(project_root, &["apply"]).status.success());
    let config_path = project_root.join(".mcp.json");
    let edited = br#"{"mcpServers":{"search":{"command":"user-edited"}}}"#;
    fs::write(&config_path, edited).unwrap();

    let revert = run_agentsync(project_root, &["revert"]);
    assert!(
        revert.status.success(),
        "{}",
        String::from_utf8_lossy(&revert.stderr)
    );
    assert_eq!(fs::read(&config_path).unwrap(), edited);
    assert!(ownership_manifest(project_root).is_file());
    assert!(String::from_utf8_lossy(&revert.stdout).contains("Skipping MCP restore"));
    let gitignore = project_root.join(".gitignore");
    if gitignore.exists() {
        assert!(
            !fs::read_to_string(&gitignore).unwrap().contains("START"),
            "a skipped MCP restore must not preserve the symlink-managed gitignore block"
        );
    }
}

#[test]
#[cfg(unix)]
fn test_apply_and_revert_dry_run_leave_mcp_and_journal_unchanged() {
    let temp_dir = TempDir::new().unwrap();
    let project_root = &temp_dir.path().join("project");
    fs::create_dir_all(project_root).unwrap();
    write_mcp_fixture(project_root);
    let mcp_path = project_root.join(".mcp.json");
    let original = fs::read(&mcp_path).unwrap();

    let apply = run_agentsync(project_root, &["apply", "--dry-run"]);
    assert!(
        apply.status.success(),
        "{}",
        String::from_utf8_lossy(&apply.stderr)
    );
    assert_eq!(fs::read(&mcp_path).unwrap(), original);
    assert!(!project_root.parent().unwrap().join(".local-data").exists());

    let revert = run_agentsync(project_root, &["revert", "--dry-run"]);
    assert!(
        revert.status.success(),
        "{}",
        String::from_utf8_lossy(&revert.stderr)
    );
    assert_eq!(fs::read(&mcp_path).unwrap(), original);
    assert!(!project_root.parent().unwrap().join(".local-data").exists());

    let real_apply = run_agentsync(project_root, &["apply"]);
    assert!(
        real_apply.status.success(),
        "{}",
        String::from_utf8_lossy(&real_apply.stderr)
    );
    let applied = fs::read(&mcp_path).unwrap();
    let manifest = ownership_manifest(project_root);
    let manifest_before = fs::read(&manifest).unwrap();
    let dry_apply = run_agentsync(project_root, &["apply", "--dry-run"]);
    assert!(
        dry_apply.status.success(),
        "{}",
        String::from_utf8_lossy(&dry_apply.stderr)
    );
    let dry_revert = run_agentsync(project_root, &["revert", "--dry-run"]);
    assert!(
        dry_revert.status.success(),
        "{}",
        String::from_utf8_lossy(&dry_revert.stderr)
    );
    assert_eq!(fs::read(&mcp_path).unwrap(), applied);
    assert_eq!(fs::read(&manifest).unwrap(), manifest_before);
}

#[test]
#[cfg(unix)]
fn test_revert_dry_run_preserves_mcp_ownership_permissions() {
    use std::os::unix::fs::PermissionsExt;

    let temp_dir = TempDir::new().unwrap();
    let project_root = &temp_dir.path().join("project");
    fs::create_dir_all(project_root).unwrap();
    write_mcp_fixture(project_root);

    let apply = run_agentsync(project_root, &["apply"]);
    assert!(
        apply.status.success(),
        "{}",
        String::from_utf8_lossy(&apply.stderr)
    );

    let manifest = ownership_manifest(project_root);
    let project_state_dir = manifest.parent().unwrap();
    let ownership_dir = project_state_dir.parent().unwrap();
    let agentsync_dir = ownership_dir.parent().unwrap();
    for directory in [agentsync_dir, ownership_dir, project_state_dir] {
        fs::set_permissions(directory, fs::Permissions::from_mode(0o755)).unwrap();
    }
    fs::set_permissions(&manifest, fs::Permissions::from_mode(0o644)).unwrap();

    let dry_revert = run_agentsync(project_root, &["revert", "--dry-run"]);
    assert!(
        dry_revert.status.success(),
        "dry-run failed:\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&dry_revert.stdout),
        String::from_utf8_lossy(&dry_revert.stderr)
    );

    for directory in [agentsync_dir, ownership_dir, project_state_dir] {
        assert_eq!(
            fs::metadata(directory).unwrap().permissions().mode() & 0o777,
            0o755,
            "dry-run changed permissions on {}",
            directory.display()
        );
    }
    assert_eq!(
        fs::metadata(&manifest).unwrap().permissions().mode() & 0o777,
        0o644,
        "dry-run changed ownership manifest permissions"
    );
}

#[test]
#[cfg(unix)]
fn test_apply_rejects_mcp_config_symlink_without_touching_target() {
    use std::os::unix::fs::symlink;

    let temp_dir = TempDir::new().unwrap();
    let project_root = &temp_dir.path().join("project");
    fs::create_dir_all(project_root).unwrap();
    write_mcp_fixture(project_root);
    let target = temp_dir.path().join("external-mcp.json");
    fs::write(&target, b"external contents\n").unwrap();
    fs::remove_file(project_root.join(".mcp.json")).unwrap();
    symlink(&target, project_root.join(".mcp.json")).unwrap();

    let apply = run_agentsync(project_root, &["apply"]);
    assert!(!apply.status.success());
    assert!(project_root.join(".mcp.json").is_symlink());
    assert_eq!(fs::read(&target).unwrap(), b"external contents\n");
    let output = format!(
        "{}{}",
        String::from_utf8_lossy(&apply.stdout),
        String::from_utf8_lossy(&apply.stderr)
    );
    assert!(
        output.contains("symlink"),
        "expected visible symlink rejection, got:\n{output}"
    );
}

#[test]
#[cfg(unix)]
fn test_apply_rejects_mcp_config_parent_symlink_without_touching_target() {
    use std::os::unix::fs::symlink;

    let temp_dir = TempDir::new().unwrap();
    let project_root = &temp_dir.path().join("project");
    let external_config_dir = temp_dir.path().join("external-config");
    fs::create_dir_all(project_root.join(".agents")).unwrap();
    fs::create_dir_all(&external_config_dir).unwrap();
    fs::write(project_root.join(".agents/AGENTS.md"), "# hello\n").unwrap();
    fs::write(
        project_root.join(".agents/agentsync.toml"),
        "[mcp]\nenabled = true\n\n[mcp_servers.tool]\ncommand = \"managed-tool\"\n\n[agents.vscode]\nenabled = true\n",
    )
    .unwrap();
    let external_config = external_config_dir.join("mcp.json");
    let original = br#"{"mcpServers":{"personal":{"command":"keep-me"}}}"#;
    fs::write(&external_config, original).unwrap();
    symlink(&external_config_dir, project_root.join(".vscode")).unwrap();

    let apply = run_agentsync(project_root, &["apply", "--no-gitignore"]);

    assert_eq!(fs::read(&external_config).unwrap(), original);
    assert!(project_root.join(".vscode").is_symlink());
    assert!(
        !apply.status.success(),
        "apply must reject a symlinked MCP parent directory"
    );
    let output = format!(
        "{}{}",
        String::from_utf8_lossy(&apply.stdout),
        String::from_utf8_lossy(&apply.stderr)
    );
    assert!(
        output.contains("symlink"),
        "expected symlink rejection, got:\n{output}"
    );
}

#[test]
#[cfg(unix)]
fn test_revert_rejects_mcp_config_parent_symlink_without_touching_target() {
    use std::os::unix::fs::symlink;

    let temp_dir = TempDir::new().unwrap();
    let project_root = &temp_dir.path().join("project");
    fs::create_dir_all(project_root.join(".agents")).unwrap();
    fs::create_dir_all(project_root.join(".vscode")).unwrap();
    fs::write(
        project_root.join(".agents/agentsync.toml"),
        "[mcp]\nenabled = true\n\n[mcp_servers.tool]\ncommand = \"managed-tool\"\n\n[agents.vscode]\nenabled = true\n",
    )
    .unwrap();
    fs::write(
        project_root.join(".vscode/mcp.json"),
        br#"{"mcpServers":{"personal":{"command":"keep-me"}}}"#,
    )
    .unwrap();

    let apply = run_agentsync(project_root, &["apply", "--no-gitignore"]);
    assert!(
        apply.status.success(),
        "{}",
        String::from_utf8_lossy(&apply.stderr)
    );
    let applied = fs::read(project_root.join(".vscode/mcp.json")).unwrap();
    fs::rename(
        project_root.join(".vscode"),
        project_root.join(".vscode.saved"),
    )
    .unwrap();
    let external_config_dir = temp_dir.path().join("external-config");
    fs::create_dir(&external_config_dir).unwrap();
    let external_config = external_config_dir.join("mcp.json");
    fs::write(&external_config, &applied).unwrap();
    symlink(&external_config_dir, project_root.join(".vscode")).unwrap();

    let revert = run_agentsync(project_root, &["revert"]);

    assert!(
        !revert.status.success(),
        "revert must reject a symlinked MCP parent directory"
    );
    assert!(project_root.join(".vscode").is_symlink());
    assert_eq!(fs::read(&external_config).unwrap(), applied);
    assert!(ownership_manifest(project_root).is_file());
}

#[test]
#[cfg(unix)]
fn test_revert_continues_after_one_mcp_record_restore_fails() {
    use std::os::unix::fs::PermissionsExt;

    let temp_dir = TempDir::new().unwrap();
    let project_root = &temp_dir.path().join("project");
    fs::create_dir_all(project_root).unwrap();
    fs::create_dir_all(project_root.join(".agents")).unwrap();
    fs::create_dir_all(project_root.join(".cursor")).unwrap();
    fs::write(project_root.join(".agents/AGENTS.md"), "# hello\n").unwrap();
    fs::write(
        project_root.join(".agents/agentsync.toml"),
        "[mcp]\nenabled = true\n\n[mcp_servers.tool]\ncommand = \"managed-tool\"\n\n[agents.claude]\nenabled = true\n\n[agents.cursor]\nenabled = true\n",
    )
    .unwrap();
    let claude_path = project_root.join(".mcp.json");
    let cursor_path = project_root.join(".cursor/mcp.json");
    let claude_original = br#"{"mcpServers":{"claude-personal":{"command":"keep-claude"}}}"#;
    let cursor_original = br#"{"mcpServers":{"cursor-personal":{"command":"keep-cursor"}}}"#;
    fs::write(&claude_path, claude_original).unwrap();
    fs::write(&cursor_path, cursor_original).unwrap();

    let apply = run_agentsync(project_root, &["apply", "--no-gitignore"]);
    assert!(
        apply.status.success(),
        "{}",
        String::from_utf8_lossy(&apply.stderr)
    );
    let claude_applied = fs::read(&claude_path).unwrap();
    let cursor_applied = fs::read(&cursor_path).unwrap();
    let manifest_path = ownership_manifest(project_root);
    let manifest: serde_json::Value =
        serde_json::from_slice(&fs::read(&manifest_path).unwrap()).unwrap();
    let records = manifest["configs"].as_object().unwrap();
    let first_record = records.iter().next().unwrap();
    let first_owner = first_record.1["agent_ids"][0].as_str().unwrap();
    let failed_parent = match first_owner {
        "claude" => project_root.to_path_buf(),
        "cursor" => project_root.join(".cursor"),
        unknown => panic!("unexpected owner id in fixture: {unknown}"),
    };
    fs::set_permissions(&failed_parent, fs::Permissions::from_mode(0o555)).unwrap();

    let revert = run_agentsync(project_root, &["revert"]);

    fs::set_permissions(&failed_parent, fs::Permissions::from_mode(0o755)).unwrap();
    assert!(
        !revert.status.success(),
        "one MCP restore failure must remain visible in the command status"
    );
    let failed_path = if first_owner == "claude" {
        &claude_path
    } else {
        &cursor_path
    };
    let successful_path = if first_owner == "claude" {
        &cursor_path
    } else {
        &claude_path
    };
    let successful_original = if first_owner == "claude" {
        cursor_original
    } else {
        claude_original
    };
    let failed_applied = if first_owner == "claude" {
        claude_applied
    } else {
        cursor_applied
    };
    assert_eq!(fs::read(successful_path).unwrap(), successful_original);
    assert_eq!(fs::read(failed_path).unwrap(), failed_applied);
    let remaining: serde_json::Value =
        serde_json::from_slice(&fs::read(&manifest_path).unwrap()).unwrap();
    assert_eq!(remaining["configs"].as_object().unwrap().len(), 1);
    assert_eq!(
        remaining["configs"]
            .as_object()
            .unwrap()
            .values()
            .next()
            .unwrap()["agent_ids"][0],
        first_owner
    );
}

#[test]
#[cfg(unix)]
fn test_apply_does_not_write_mcp_when_ownership_store_cannot_be_opened() {
    let temp_dir = TempDir::new().unwrap();
    let project_root = &temp_dir.path().join("project");
    fs::create_dir_all(project_root).unwrap();
    write_mcp_fixture(project_root);
    let config_path = project_root.join(".mcp.json");
    let original = fs::read(&config_path).unwrap();
    fs::write(
        project_root.parent().unwrap().join(".local-data"),
        b"not a directory",
    )
    .unwrap();

    let apply = run_agentsync(project_root, &["apply"]);

    assert!(!apply.status.success());
    assert_eq!(fs::read(&config_path).unwrap(), original);
    let output = format!(
        "{}{}",
        String::from_utf8_lossy(&apply.stdout),
        String::from_utf8_lossy(&apply.stderr)
    );
    assert!(
        output.contains("ownership") || output.contains("local data"),
        "{output}"
    );
}

#[test]
#[cfg(unix)]
fn test_apply_fails_when_mcp_parent_cannot_be_created_after_journaling() {
    use std::os::unix::fs::PermissionsExt;

    let temp_dir = TempDir::new().unwrap();
    let project_root = &temp_dir.path().join("project");
    fs::create_dir_all(project_root).unwrap();
    fs::create_dir_all(project_root.join(".agents")).unwrap();
    fs::write(
        project_root.join(".agents/agentsync.toml"),
        "[mcp]\nenabled = true\n\n[mcp_servers.search]\ncommand = \"managed-search\"\n\n[agents.codex]\nenabled = true\n",
    )
    .unwrap();
    let local_data = project_root.parent().unwrap().join(".local-data");
    fs::create_dir(&local_data).unwrap();
    fs::set_permissions(&local_data, fs::Permissions::from_mode(0o700)).unwrap();
    fs::set_permissions(project_root, fs::Permissions::from_mode(0o555)).unwrap();

    let apply = run_agentsync(project_root, &["apply", "--no-gitignore"]);

    fs::set_permissions(project_root, fs::Permissions::from_mode(0o755)).unwrap();
    assert!(
        !apply.status.success(),
        "failed MCP parent creation must fail the apply command\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&apply.stdout),
        String::from_utf8_lossy(&apply.stderr)
    );
    assert!(!project_root.join(".codex/config.toml").exists());
    assert!(ownership_manifest(project_root).is_file());
}

#[test]
#[cfg(unix)]
fn test_revert_rejects_replaced_mcp_config_symlink() {
    use std::os::unix::fs::symlink;

    let temp_dir = TempDir::new().unwrap();
    let project_root = &temp_dir.path().join("project");
    fs::create_dir_all(project_root).unwrap();
    write_mcp_fixture(project_root);
    assert!(run_agentsync(project_root, &["apply"]).status.success());
    let target = temp_dir.path().join("external-mcp.json");
    fs::write(&target, b"external contents\n").unwrap();
    fs::remove_file(project_root.join(".mcp.json")).unwrap();
    symlink(&target, project_root.join(".mcp.json")).unwrap();

    let revert = run_agentsync(project_root, &["revert"]);
    assert!(!revert.status.success());
    assert!(project_root.join(".mcp.json").is_symlink());
    assert_eq!(fs::read(&target).unwrap(), b"external contents\n");
    let output = format!(
        "{}{}",
        String::from_utf8_lossy(&revert.stdout),
        String::from_utf8_lossy(&revert.stderr)
    );
    assert!(
        output.contains("symlink"),
        "expected visible symlink rejection, got:\n{output}"
    );
    assert!(ownership_manifest(project_root).is_file());
}

#[test]
#[cfg(unix)]
fn test_revert_filter_skips_shared_mcp_path_until_all_owners_selected() {
    let temp_dir = TempDir::new().unwrap();
    let project_root = &temp_dir.path().join("project");
    fs::create_dir_all(project_root).unwrap();
    fs::create_dir_all(project_root.join(".agents")).unwrap();
    fs::write(project_root.join(".agents/AGENTS.md"), "# hello\n").unwrap();
    fs::write(
        project_root.join(".agents/agentsync.toml"),
        "[mcp]\nenabled = true\n\n[mcp_servers.tool]\ncommand = \"managed-tool\"\n\n[agents.copilot]\nenabled = true\n\n[agents.vscode]\nenabled = true\n",
    )
    .unwrap();
    fs::create_dir_all(project_root.join(".vscode")).unwrap();
    let original = br#"{"mcpServers":{"mine":{"command":"mine"}}}"#;
    fs::write(project_root.join(".vscode/mcp.json"), original).unwrap();

    let apply = run_agentsync(project_root, &["apply"]);
    assert!(
        apply.status.success(),
        "{}",
        String::from_utf8_lossy(&apply.stderr)
    );
    let applied = fs::read(project_root.join(".vscode/mcp.json")).unwrap();
    let filtered = run_agentsync(project_root, &["revert", "--agents", "copilot"]);
    assert!(
        filtered.status.success(),
        "{}",
        String::from_utf8_lossy(&filtered.stderr)
    );
    assert_eq!(
        fs::read(project_root.join(".vscode/mcp.json")).unwrap(),
        applied
    );
    assert!(ownership_manifest(project_root).is_file());
    assert!(String::from_utf8_lossy(&filtered.stdout).contains("not all recorded agents"));

    let full = run_agentsync(project_root, &["revert"]);
    assert!(
        full.status.success(),
        "{}",
        String::from_utf8_lossy(&full.stderr)
    );
    assert_eq!(
        fs::read(project_root.join(".vscode/mcp.json")).unwrap(),
        original
    );
}

#[test]
#[cfg(unix)]
fn test_reapply_identical_shared_config_adds_new_owner() {
    let temp_dir = TempDir::new().unwrap();
    let project_root = &temp_dir.path().join("project");
    fs::create_dir_all(project_root).unwrap();
    fs::create_dir_all(project_root.join(".agents")).unwrap();
    fs::write(project_root.join(".agents/AGENTS.md"), "# hello\n").unwrap();
    let config_path = project_root.join(".agents/agentsync.toml");
    fs::write(
        &config_path,
        "[mcp]\nenabled = true\n\n[mcp_servers.tool]\ncommand = \"managed-tool\"\n\n[agents.vscode]\nenabled = true\n",
    )
    .unwrap();
    fs::create_dir_all(project_root.join(".vscode")).unwrap();
    fs::write(
        project_root.join(".vscode/mcp.json"),
        br#"{"mcpServers":{"tool":{"command":"old-tool"}}}"#,
    )
    .unwrap();

    let first_apply = run_agentsync(project_root, &["apply"]);
    assert!(
        first_apply.status.success(),
        "{}",
        String::from_utf8_lossy(&first_apply.stderr)
    );
    let applied = fs::read(project_root.join(".vscode/mcp.json")).unwrap();

    fs::write(
        &config_path,
        "[mcp]\nenabled = true\n\n[mcp_servers.tool]\ncommand = \"managed-tool\"\n\n[agents.copilot]\nenabled = true\n\n[agents.vscode]\nenabled = true\n",
    )
    .unwrap();
    let manifest = ownership_manifest(project_root);
    let manifest_before_dry_run = fs::read(&manifest).unwrap();
    let dry_apply = run_agentsync(project_root, &["apply", "--dry-run"]);
    assert!(
        dry_apply.status.success(),
        "{}",
        String::from_utf8_lossy(&dry_apply.stderr)
    );
    assert_eq!(fs::read(&manifest).unwrap(), manifest_before_dry_run);
    assert_eq!(
        fs::read(project_root.join(".vscode/mcp.json")).unwrap(),
        applied
    );

    let second_apply = run_agentsync(project_root, &["apply"]);
    assert!(
        second_apply.status.success(),
        "{}",
        String::from_utf8_lossy(&second_apply.stderr)
    );
    assert_eq!(
        fs::read(project_root.join(".vscode/mcp.json")).unwrap(),
        applied
    );

    let filtered_revert = run_agentsync(project_root, &["revert", "--agents", "vscode"]);
    assert!(
        filtered_revert.status.success(),
        "{}",
        String::from_utf8_lossy(&filtered_revert.stderr)
    );
    assert_eq!(
        fs::read(project_root.join(".vscode/mcp.json")).unwrap(),
        applied,
        "reverting only VS Code must not restore a config now shared with Copilot"
    );
    assert!(ownership_manifest(project_root).is_file());
    assert!(String::from_utf8_lossy(&filtered_revert.stdout).contains("not all recorded agents"));
}

#[test]
#[cfg(unix)]
fn test_disabled_configured_agent_is_recorded_as_shared_mcp_owner() {
    let temp_dir = TempDir::new().unwrap();
    let project_root = &temp_dir.path().join("project");
    fs::create_dir_all(project_root).unwrap();
    fs::create_dir_all(project_root.join(".agents")).unwrap();
    fs::write(project_root.join(".agents/AGENTS.md"), "# hello\n").unwrap();
    fs::write(
        project_root.join(".agents/agentsync.toml"),
        "[mcp]\nenabled = true\n\n[mcp_servers.tool]\ncommand = \"managed-tool\"\n\n[agents.claude]\nenabled = true\n\n[agents.minimax]\nenabled = false\n",
    )
    .unwrap();
    fs::write(
        project_root.join(".mcp.json"),
        br#"{"mcpServers":{"mine":{"command":"mine"}}}"#,
    )
    .unwrap();

    let apply = run_agentsync(project_root, &["apply"]);
    assert!(
        apply.status.success(),
        "{}",
        String::from_utf8_lossy(&apply.stderr)
    );
    let applied = fs::read(project_root.join(".mcp.json")).unwrap();
    let filtered = run_agentsync(project_root, &["revert", "--agents", "claude"]);
    assert!(
        filtered.status.success(),
        "{}",
        String::from_utf8_lossy(&filtered.stderr)
    );
    assert_eq!(fs::read(project_root.join(".mcp.json")).unwrap(), applied);
    assert!(ownership_manifest(project_root).is_file());

    let full = run_agentsync(project_root, &["revert"]);
    assert!(
        full.status.success(),
        "{}",
        String::from_utf8_lossy(&full.stderr)
    );
    assert_eq!(
        fs::read(project_root.join(".mcp.json")).unwrap(),
        br#"{"mcpServers":{"mine":{"command":"mine"}}}"#
    );
}

#[test]
#[cfg(unix)]
fn test_post_apply_edit_to_new_mcp_config_is_not_removed() {
    let temp_dir = TempDir::new().unwrap();
    let project_root = &temp_dir.path().join("project");
    fs::create_dir_all(project_root).unwrap();
    write_mcp_fixture(project_root);
    fs::remove_file(project_root.join(".mcp.json")).unwrap();
    assert!(run_agentsync(project_root, &["apply"]).status.success());
    let edited = br#"{"mcpServers":{"personal":{"command":"keep-me"}}}"#;
    fs::write(project_root.join(".mcp.json"), edited).unwrap();

    let revert = run_agentsync(project_root, &["revert"]);
    assert!(
        revert.status.success(),
        "{}",
        String::from_utf8_lossy(&revert.stderr)
    );
    assert_eq!(fs::read(project_root.join(".mcp.json")).unwrap(), edited);
    assert!(ownership_manifest(project_root).is_file());
}

#[test]
#[cfg(unix)]
fn test_revert_restores_journal_when_mcp_is_disabled_in_current_config() {
    let temp_dir = TempDir::new().unwrap();
    let project_root = &temp_dir.path().join("project");
    fs::create_dir_all(project_root).unwrap();
    write_mcp_fixture(project_root);
    let original = fs::read(project_root.join(".mcp.json")).unwrap();
    assert!(run_agentsync(project_root, &["apply"]).status.success());
    let config_path = project_root.join(".agents/agentsync.toml");
    fs::write(
        &config_path,
        "[mcp]\nenabled = false\n\n[agents.claude]\nenabled = false\n",
    )
    .unwrap();

    let revert = run_agentsync(project_root, &["revert"]);
    assert!(
        revert.status.success(),
        "{}",
        String::from_utf8_lossy(&revert.stderr)
    );
    assert_eq!(fs::read(project_root.join(".mcp.json")).unwrap(), original);
    assert!(!ownership_manifest(project_root).exists());
}

#[test]
#[cfg(unix)]
fn test_revert_without_journal_warns_and_leaves_legacy_mcp_unchanged() {
    let temp_dir = TempDir::new().unwrap();
    let project_root = &temp_dir.path().join("project");
    fs::create_dir_all(project_root).unwrap();
    write_mcp_fixture(project_root);
    let original =
        br#"{"mcpServers":{"search":{"command":"managed-search","args":["--managed"]}}}"#;
    fs::write(project_root.join(".mcp.json"), original).unwrap();

    let revert = run_agentsync(project_root, &["revert"]);
    assert!(
        revert.status.success(),
        "{}",
        String::from_utf8_lossy(&revert.stderr)
    );
    assert_eq!(fs::read(project_root.join(".mcp.json")).unwrap(), original);
    assert!(!project_root.parent().unwrap().join(".local-data").exists());
    assert!(String::from_utf8_lossy(&revert.stdout).contains("No MCP ownership journal found"));
}

#[test]
#[cfg(unix)]
fn test_revert_prunes_journal_after_file_was_already_restored() {
    let temp_dir = TempDir::new().unwrap();
    let project_root = &temp_dir.path().join("project");
    fs::create_dir_all(project_root).unwrap();
    write_mcp_fixture(project_root);
    let original = fs::read(project_root.join(".mcp.json")).unwrap();
    assert!(run_agentsync(project_root, &["apply"]).status.success());
    fs::write(project_root.join(".mcp.json"), &original).unwrap();
    let manifest = ownership_manifest(project_root);
    assert!(manifest.is_file());

    let revert = run_agentsync(project_root, &["revert"]);
    assert!(
        revert.status.success(),
        "{}",
        String::from_utf8_lossy(&revert.stderr)
    );
    assert_eq!(fs::read(project_root.join(".mcp.json")).unwrap(), original);
    assert!(!manifest.exists());
}

#[cfg(unix)]
fn write_two_agent_fixture(project_root: &Path) {
    fs::create_dir_all(project_root.join(".agents")).unwrap();
    fs::write(project_root.join(".agents/AGENTS.md"), "# hello\n").unwrap();
    fs::write(
        project_root.join(".agents/agentsync.toml"),
        "source_dir = \".\"\n\n[agents.claude]\nenabled = true\n\n[agents.claude.targets.instructions]\nsource = \"AGENTS.md\"\ndestination = \"CLAUDE.md\"\ntype = \"symlink\"\n\n[agents.copilot]\nenabled = true\n\n[agents.copilot.targets.instructions]\nsource = \"AGENTS.md\"\ndestination = \"COPILOT.md\"\ntype = \"symlink\"\n",
    )
    .unwrap();
    fs::write(project_root.join("CLAUDE.md"), "original-claude\n").unwrap();
    fs::write(project_root.join("COPILOT.md"), "original-copilot\n").unwrap();
}

#[test]
#[cfg(unix)]
fn test_revert_agents_filter_limits_scope() {
    let temp_dir = TempDir::new().unwrap();
    let project_root = &temp_dir.path().join("project");
    fs::create_dir_all(project_root).unwrap();
    write_two_agent_fixture(project_root);
    assert!(run_agentsync(project_root, &["apply"]).status.success());
    assert!(project_root.join("CLAUDE.md").is_symlink());
    assert!(project_root.join("COPILOT.md").is_symlink());

    let revert = run_agentsync(project_root, &["revert", "--agents", "claude"]);
    assert!(
        revert.status.success(),
        "revert --agents failed:\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&revert.stdout),
        String::from_utf8_lossy(&revert.stderr)
    );
    // Claude restored; copilot untouched.
    assert_eq!(
        fs::read_to_string(project_root.join("CLAUDE.md")).unwrap(),
        "original-claude\n"
    );
    assert!(project_root.join("COPILOT.md").is_symlink());
    assert!(project_root.join("COPILOT.md.bak").exists());
}

#[test]
#[cfg(unix)]
fn test_revert_leaves_repointed_symlink_untouched() {
    use std::os::unix::fs::symlink;

    let temp_dir = TempDir::new().unwrap();
    let project_root = &temp_dir.path().join("project");
    fs::create_dir_all(project_root).unwrap();
    write_fixture(project_root);
    assert!(run_agentsync(project_root, &["apply"]).status.success());
    assert!(project_root.join("CLAUDE.md").is_symlink());
    assert!(project_root.join("CLAUDE.md.bak").exists());

    // User repoints the managed symlink elsewhere after apply.
    fs::remove_file(project_root.join("CLAUDE.md")).unwrap();
    fs::write(project_root.join("ELSEWHERE.md"), "elsewhere\n").unwrap();
    symlink("ELSEWHERE.md", project_root.join("CLAUDE.md")).unwrap();
    assert!(project_root.join("CLAUDE.md").is_symlink());

    let revert = run_agentsync(project_root, &["revert"]);
    assert!(
        revert.status.success(),
        "revert failed:\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&revert.stdout),
        String::from_utf8_lossy(&revert.stderr)
    );
    // Neither the repointed link nor its backup is touched, and the skip is
    // warned about on stdout.
    assert!(project_root.join("CLAUDE.md").is_symlink());
    assert_eq!(
        fs::read_link(project_root.join("CLAUDE.md")).unwrap(),
        PathBuf::from("ELSEWHERE.md")
    );
    assert_eq!(
        fs::read_to_string(project_root.join("CLAUDE.md.bak")).unwrap(),
        "original\n"
    );
    let stdout = String::from_utf8_lossy(&revert.stdout);
    assert!(
        stdout.contains("Skipping unmanaged symlink"),
        "expected unmanaged-symlink skip warning, got:\n{stdout}"
    );
    let gitignore = fs::read_to_string(project_root.join(".gitignore")).unwrap();
    assert!(
        gitignore.contains("# START AI Agent Symlinks"),
        "managed gitignore block must remain when revert skips a destination"
    );
}
